// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aepsAxis.proto

package com.iserveu.grpc_stub;

/**
 * Protobuf type {@code AxisRequest}
 */
public  final class AxisRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AxisRequest)
    AxisRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AxisRequest.newBuilder() to construct.
  private AxisRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AxisRequest() {
    aadhaar_ = "";
    iin_ = "";
    amount_ = 0;
    txnId_ = 0L;
    latitude_ = "";
    longitude_ = "";
    merchantId_ = 0L;
    bankName_ = "";
    mobileNo_ = "";
    pidData_ = "";
    ipAddress_ = "";
    imeiMac_ = "";
    deviceNo_ = "";
    userId_ = 0L;
    userName_ = "";
    city_ = "";
    state_ = "";
    stan_ = 0;
    bcRrn_ = "";
    country_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AxisRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aadhaar_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            iin_ = s;
            break;
          }
          case 24: {

            amount_ = input.readInt32();
            break;
          }
          case 32: {

            txnId_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            latitude_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            longitude_ = s;
            break;
          }
          case 56: {

            merchantId_ = input.readInt64();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            bankName_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            mobileNo_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            pidData_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            ipAddress_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            imeiMac_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceNo_ = s;
            break;
          }
          case 112: {

            userId_ = input.readInt64();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            state_ = s;
            break;
          }
          case 144: {

            stan_ = input.readInt32();
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            bcRrn_ = s;
            break;
          }
          case 162: {
            java.lang.String s = input.readStringRequireUtf8();

            country_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iserveu.grpc_stub.AepsAxis.internal_static_AxisRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iserveu.grpc_stub.AepsAxis.internal_static_AxisRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iserveu.grpc_stub.AxisRequest.class, com.iserveu.grpc_stub.AxisRequest.Builder.class);
  }

  public static final int AADHAAR_FIELD_NUMBER = 1;
  private volatile java.lang.Object aadhaar_;
  /**
   * <code>string aadhaar = 1;</code>
   */
  public java.lang.String getAadhaar() {
    java.lang.Object ref = aadhaar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aadhaar_ = s;
      return s;
    }
  }
  /**
   * <code>string aadhaar = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAadhaarBytes() {
    java.lang.Object ref = aadhaar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aadhaar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IIN_FIELD_NUMBER = 2;
  private volatile java.lang.Object iin_;
  /**
   * <code>string iin = 2;</code>
   */
  public java.lang.String getIin() {
    java.lang.Object ref = iin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iin_ = s;
      return s;
    }
  }
  /**
   * <code>string iin = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIinBytes() {
    java.lang.Object ref = iin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private int amount_;
  /**
   * <code>int32 amount = 3;</code>
   */
  public int getAmount() {
    return amount_;
  }

  public static final int TXNID_FIELD_NUMBER = 4;
  private long txnId_;
  /**
   * <code>int64 txnId = 4;</code>
   */
  public long getTxnId() {
    return txnId_;
  }

  public static final int LATITUDE_FIELD_NUMBER = 5;
  private volatile java.lang.Object latitude_;
  /**
   * <code>string latitude = 5;</code>
   */
  public java.lang.String getLatitude() {
    java.lang.Object ref = latitude_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      latitude_ = s;
      return s;
    }
  }
  /**
   * <code>string latitude = 5;</code>
   */
  public com.google.protobuf.ByteString
      getLatitudeBytes() {
    java.lang.Object ref = latitude_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      latitude_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LONGITUDE_FIELD_NUMBER = 6;
  private volatile java.lang.Object longitude_;
  /**
   * <code>string longitude = 6;</code>
   */
  public java.lang.String getLongitude() {
    java.lang.Object ref = longitude_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      longitude_ = s;
      return s;
    }
  }
  /**
   * <code>string longitude = 6;</code>
   */
  public com.google.protobuf.ByteString
      getLongitudeBytes() {
    java.lang.Object ref = longitude_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      longitude_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MERCHANTID_FIELD_NUMBER = 7;
  private long merchantId_;
  /**
   * <code>int64 merchantId = 7;</code>
   */
  public long getMerchantId() {
    return merchantId_;
  }

  public static final int BANKNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object bankName_;
  /**
   * <code>string bankName = 8;</code>
   */
  public java.lang.String getBankName() {
    java.lang.Object ref = bankName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bankName_ = s;
      return s;
    }
  }
  /**
   * <code>string bankName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getBankNameBytes() {
    java.lang.Object ref = bankName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bankName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOBILENO_FIELD_NUMBER = 9;
  private volatile java.lang.Object mobileNo_;
  /**
   * <code>string mobileNo = 9;</code>
   */
  public java.lang.String getMobileNo() {
    java.lang.Object ref = mobileNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mobileNo_ = s;
      return s;
    }
  }
  /**
   * <code>string mobileNo = 9;</code>
   */
  public com.google.protobuf.ByteString
      getMobileNoBytes() {
    java.lang.Object ref = mobileNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mobileNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PIDDATA_FIELD_NUMBER = 10;
  private volatile java.lang.Object pidData_;
  /**
   * <code>string pidData = 10;</code>
   */
  public java.lang.String getPidData() {
    java.lang.Object ref = pidData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pidData_ = s;
      return s;
    }
  }
  /**
   * <code>string pidData = 10;</code>
   */
  public com.google.protobuf.ByteString
      getPidDataBytes() {
    java.lang.Object ref = pidData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pidData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IPADDRESS_FIELD_NUMBER = 11;
  private volatile java.lang.Object ipAddress_;
  /**
   * <code>string ipAddress = 11;</code>
   */
  public java.lang.String getIpAddress() {
    java.lang.Object ref = ipAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string ipAddress = 11;</code>
   */
  public com.google.protobuf.ByteString
      getIpAddressBytes() {
    java.lang.Object ref = ipAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMEIMAC_FIELD_NUMBER = 12;
  private volatile java.lang.Object imeiMac_;
  /**
   * <code>string imeiMac = 12;</code>
   */
  public java.lang.String getImeiMac() {
    java.lang.Object ref = imeiMac_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imeiMac_ = s;
      return s;
    }
  }
  /**
   * <code>string imeiMac = 12;</code>
   */
  public com.google.protobuf.ByteString
      getImeiMacBytes() {
    java.lang.Object ref = imeiMac_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imeiMac_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICENO_FIELD_NUMBER = 13;
  private volatile java.lang.Object deviceNo_;
  /**
   * <code>string deviceNo = 13;</code>
   */
  public java.lang.String getDeviceNo() {
    java.lang.Object ref = deviceNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceNo_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceNo = 13;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceNoBytes() {
    java.lang.Object ref = deviceNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 14;
  private long userId_;
  /**
   * <code>int64 userId = 14;</code>
   */
  public long getUserId() {
    return userId_;
  }

  public static final int USERNAME_FIELD_NUMBER = 15;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 15;</code>
   */
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 15;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 16;
  private volatile java.lang.Object city_;
  /**
   * <code>string city = 16;</code>
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 16;</code>
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_FIELD_NUMBER = 17;
  private volatile java.lang.Object state_;
  /**
   * <code>string state = 17;</code>
   */
  public java.lang.String getState() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      state_ = s;
      return s;
    }
  }
  /**
   * <code>string state = 17;</code>
   */
  public com.google.protobuf.ByteString
      getStateBytes() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      state_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAN_FIELD_NUMBER = 18;
  private int stan_;
  /**
   * <code>int32 stan = 18;</code>
   */
  public int getStan() {
    return stan_;
  }

  public static final int BCRRN_FIELD_NUMBER = 19;
  private volatile java.lang.Object bcRrn_;
  /**
   * <code>string bcRrn = 19;</code>
   */
  public java.lang.String getBcRrn() {
    java.lang.Object ref = bcRrn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bcRrn_ = s;
      return s;
    }
  }
  /**
   * <code>string bcRrn = 19;</code>
   */
  public com.google.protobuf.ByteString
      getBcRrnBytes() {
    java.lang.Object ref = bcRrn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bcRrn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTRY_FIELD_NUMBER = 20;
  private volatile java.lang.Object country_;
  /**
   * <code>string country = 20;</code>
   */
  public java.lang.String getCountry() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      country_ = s;
      return s;
    }
  }
  /**
   * <code>string country = 20;</code>
   */
  public com.google.protobuf.ByteString
      getCountryBytes() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      country_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAadhaarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aadhaar_);
    }
    if (!getIinBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iin_);
    }
    if (amount_ != 0) {
      output.writeInt32(3, amount_);
    }
    if (txnId_ != 0L) {
      output.writeInt64(4, txnId_);
    }
    if (!getLatitudeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, latitude_);
    }
    if (!getLongitudeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, longitude_);
    }
    if (merchantId_ != 0L) {
      output.writeInt64(7, merchantId_);
    }
    if (!getBankNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, bankName_);
    }
    if (!getMobileNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, mobileNo_);
    }
    if (!getPidDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, pidData_);
    }
    if (!getIpAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, ipAddress_);
    }
    if (!getImeiMacBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, imeiMac_);
    }
    if (!getDeviceNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, deviceNo_);
    }
    if (userId_ != 0L) {
      output.writeInt64(14, userId_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, userName_);
    }
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, city_);
    }
    if (!getStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, state_);
    }
    if (stan_ != 0) {
      output.writeInt32(18, stan_);
    }
    if (!getBcRrnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, bcRrn_);
    }
    if (!getCountryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, country_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAadhaarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aadhaar_);
    }
    if (!getIinBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iin_);
    }
    if (amount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, amount_);
    }
    if (txnId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, txnId_);
    }
    if (!getLatitudeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, latitude_);
    }
    if (!getLongitudeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, longitude_);
    }
    if (merchantId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, merchantId_);
    }
    if (!getBankNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, bankName_);
    }
    if (!getMobileNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, mobileNo_);
    }
    if (!getPidDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, pidData_);
    }
    if (!getIpAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, ipAddress_);
    }
    if (!getImeiMacBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, imeiMac_);
    }
    if (!getDeviceNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, deviceNo_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, userId_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, userName_);
    }
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, city_);
    }
    if (!getStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, state_);
    }
    if (stan_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(18, stan_);
    }
    if (!getBcRrnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, bcRrn_);
    }
    if (!getCountryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, country_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iserveu.grpc_stub.AxisRequest)) {
      return super.equals(obj);
    }
    com.iserveu.grpc_stub.AxisRequest other = (com.iserveu.grpc_stub.AxisRequest) obj;

    boolean result = true;
    result = result && getAadhaar()
        .equals(other.getAadhaar());
    result = result && getIin()
        .equals(other.getIin());
    result = result && (getAmount()
        == other.getAmount());
    result = result && (getTxnId()
        == other.getTxnId());
    result = result && getLatitude()
        .equals(other.getLatitude());
    result = result && getLongitude()
        .equals(other.getLongitude());
    result = result && (getMerchantId()
        == other.getMerchantId());
    result = result && getBankName()
        .equals(other.getBankName());
    result = result && getMobileNo()
        .equals(other.getMobileNo());
    result = result && getPidData()
        .equals(other.getPidData());
    result = result && getIpAddress()
        .equals(other.getIpAddress());
    result = result && getImeiMac()
        .equals(other.getImeiMac());
    result = result && getDeviceNo()
        .equals(other.getDeviceNo());
    result = result && (getUserId()
        == other.getUserId());
    result = result && getUserName()
        .equals(other.getUserName());
    result = result && getCity()
        .equals(other.getCity());
    result = result && getState()
        .equals(other.getState());
    result = result && (getStan()
        == other.getStan());
    result = result && getBcRrn()
        .equals(other.getBcRrn());
    result = result && getCountry()
        .equals(other.getCountry());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AADHAAR_FIELD_NUMBER;
    hash = (53 * hash) + getAadhaar().hashCode();
    hash = (37 * hash) + IIN_FIELD_NUMBER;
    hash = (53 * hash) + getIin().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount();
    hash = (37 * hash) + TXNID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTxnId());
    hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getLatitude().hashCode();
    hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getLongitude().hashCode();
    hash = (37 * hash) + MERCHANTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMerchantId());
    hash = (37 * hash) + BANKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBankName().hashCode();
    hash = (37 * hash) + MOBILENO_FIELD_NUMBER;
    hash = (53 * hash) + getMobileNo().hashCode();
    hash = (37 * hash) + PIDDATA_FIELD_NUMBER;
    hash = (53 * hash) + getPidData().hashCode();
    hash = (37 * hash) + IPADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getIpAddress().hashCode();
    hash = (37 * hash) + IMEIMAC_FIELD_NUMBER;
    hash = (53 * hash) + getImeiMac().hashCode();
    hash = (37 * hash) + DEVICENO_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceNo().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + getState().hashCode();
    hash = (37 * hash) + STAN_FIELD_NUMBER;
    hash = (53 * hash) + getStan();
    hash = (37 * hash) + BCRRN_FIELD_NUMBER;
    hash = (53 * hash) + getBcRrn().hashCode();
    hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getCountry().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iserveu.grpc_stub.AxisRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iserveu.grpc_stub.AxisRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AxisRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AxisRequest)
      com.iserveu.grpc_stub.AxisRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iserveu.grpc_stub.AepsAxis.internal_static_AxisRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iserveu.grpc_stub.AepsAxis.internal_static_AxisRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iserveu.grpc_stub.AxisRequest.class, com.iserveu.grpc_stub.AxisRequest.Builder.class);
    }

    // Construct using com.iserveu.grpc_stub.AxisRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aadhaar_ = "";

      iin_ = "";

      amount_ = 0;

      txnId_ = 0L;

      latitude_ = "";

      longitude_ = "";

      merchantId_ = 0L;

      bankName_ = "";

      mobileNo_ = "";

      pidData_ = "";

      ipAddress_ = "";

      imeiMac_ = "";

      deviceNo_ = "";

      userId_ = 0L;

      userName_ = "";

      city_ = "";

      state_ = "";

      stan_ = 0;

      bcRrn_ = "";

      country_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iserveu.grpc_stub.AepsAxis.internal_static_AxisRequest_descriptor;
    }

    @java.lang.Override
    public com.iserveu.grpc_stub.AxisRequest getDefaultInstanceForType() {
      return com.iserveu.grpc_stub.AxisRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.iserveu.grpc_stub.AxisRequest build() {
      com.iserveu.grpc_stub.AxisRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iserveu.grpc_stub.AxisRequest buildPartial() {
      com.iserveu.grpc_stub.AxisRequest result = new com.iserveu.grpc_stub.AxisRequest(this);
      result.aadhaar_ = aadhaar_;
      result.iin_ = iin_;
      result.amount_ = amount_;
      result.txnId_ = txnId_;
      result.latitude_ = latitude_;
      result.longitude_ = longitude_;
      result.merchantId_ = merchantId_;
      result.bankName_ = bankName_;
      result.mobileNo_ = mobileNo_;
      result.pidData_ = pidData_;
      result.ipAddress_ = ipAddress_;
      result.imeiMac_ = imeiMac_;
      result.deviceNo_ = deviceNo_;
      result.userId_ = userId_;
      result.userName_ = userName_;
      result.city_ = city_;
      result.state_ = state_;
      result.stan_ = stan_;
      result.bcRrn_ = bcRrn_;
      result.country_ = country_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iserveu.grpc_stub.AxisRequest) {
        return mergeFrom((com.iserveu.grpc_stub.AxisRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iserveu.grpc_stub.AxisRequest other) {
      if (other == com.iserveu.grpc_stub.AxisRequest.getDefaultInstance()) return this;
      if (!other.getAadhaar().isEmpty()) {
        aadhaar_ = other.aadhaar_;
        onChanged();
      }
      if (!other.getIin().isEmpty()) {
        iin_ = other.iin_;
        onChanged();
      }
      if (other.getAmount() != 0) {
        setAmount(other.getAmount());
      }
      if (other.getTxnId() != 0L) {
        setTxnId(other.getTxnId());
      }
      if (!other.getLatitude().isEmpty()) {
        latitude_ = other.latitude_;
        onChanged();
      }
      if (!other.getLongitude().isEmpty()) {
        longitude_ = other.longitude_;
        onChanged();
      }
      if (other.getMerchantId() != 0L) {
        setMerchantId(other.getMerchantId());
      }
      if (!other.getBankName().isEmpty()) {
        bankName_ = other.bankName_;
        onChanged();
      }
      if (!other.getMobileNo().isEmpty()) {
        mobileNo_ = other.mobileNo_;
        onChanged();
      }
      if (!other.getPidData().isEmpty()) {
        pidData_ = other.pidData_;
        onChanged();
      }
      if (!other.getIpAddress().isEmpty()) {
        ipAddress_ = other.ipAddress_;
        onChanged();
      }
      if (!other.getImeiMac().isEmpty()) {
        imeiMac_ = other.imeiMac_;
        onChanged();
      }
      if (!other.getDeviceNo().isEmpty()) {
        deviceNo_ = other.deviceNo_;
        onChanged();
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getState().isEmpty()) {
        state_ = other.state_;
        onChanged();
      }
      if (other.getStan() != 0) {
        setStan(other.getStan());
      }
      if (!other.getBcRrn().isEmpty()) {
        bcRrn_ = other.bcRrn_;
        onChanged();
      }
      if (!other.getCountry().isEmpty()) {
        country_ = other.country_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iserveu.grpc_stub.AxisRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iserveu.grpc_stub.AxisRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object aadhaar_ = "";
    /**
     * <code>string aadhaar = 1;</code>
     */
    public java.lang.String getAadhaar() {
      java.lang.Object ref = aadhaar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aadhaar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aadhaar = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAadhaarBytes() {
      java.lang.Object ref = aadhaar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aadhaar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aadhaar = 1;</code>
     */
    public Builder setAadhaar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aadhaar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string aadhaar = 1;</code>
     */
    public Builder clearAadhaar() {
      
      aadhaar_ = getDefaultInstance().getAadhaar();
      onChanged();
      return this;
    }
    /**
     * <code>string aadhaar = 1;</code>
     */
    public Builder setAadhaarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aadhaar_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object iin_ = "";
    /**
     * <code>string iin = 2;</code>
     */
    public java.lang.String getIin() {
      java.lang.Object ref = iin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string iin = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIinBytes() {
      java.lang.Object ref = iin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string iin = 2;</code>
     */
    public Builder setIin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string iin = 2;</code>
     */
    public Builder clearIin() {
      
      iin_ = getDefaultInstance().getIin();
      onChanged();
      return this;
    }
    /**
     * <code>string iin = 2;</code>
     */
    public Builder setIinBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iin_ = value;
      onChanged();
      return this;
    }

    private int amount_ ;
    /**
     * <code>int32 amount = 3;</code>
     */
    public int getAmount() {
      return amount_;
    }
    /**
     * <code>int32 amount = 3;</code>
     */
    public Builder setAmount(int value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 amount = 3;</code>
     */
    public Builder clearAmount() {
      
      amount_ = 0;
      onChanged();
      return this;
    }

    private long txnId_ ;
    /**
     * <code>int64 txnId = 4;</code>
     */
    public long getTxnId() {
      return txnId_;
    }
    /**
     * <code>int64 txnId = 4;</code>
     */
    public Builder setTxnId(long value) {
      
      txnId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 txnId = 4;</code>
     */
    public Builder clearTxnId() {
      
      txnId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object latitude_ = "";
    /**
     * <code>string latitude = 5;</code>
     */
    public java.lang.String getLatitude() {
      java.lang.Object ref = latitude_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latitude_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string latitude = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLatitudeBytes() {
      java.lang.Object ref = latitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string latitude = 5;</code>
     */
    public Builder setLatitude(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      latitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string latitude = 5;</code>
     */
    public Builder clearLatitude() {
      
      latitude_ = getDefaultInstance().getLatitude();
      onChanged();
      return this;
    }
    /**
     * <code>string latitude = 5;</code>
     */
    public Builder setLatitudeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      latitude_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object longitude_ = "";
    /**
     * <code>string longitude = 6;</code>
     */
    public java.lang.String getLongitude() {
      java.lang.Object ref = longitude_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longitude_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string longitude = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLongitudeBytes() {
      java.lang.Object ref = longitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string longitude = 6;</code>
     */
    public Builder setLongitude(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      longitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string longitude = 6;</code>
     */
    public Builder clearLongitude() {
      
      longitude_ = getDefaultInstance().getLongitude();
      onChanged();
      return this;
    }
    /**
     * <code>string longitude = 6;</code>
     */
    public Builder setLongitudeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      longitude_ = value;
      onChanged();
      return this;
    }

    private long merchantId_ ;
    /**
     * <code>int64 merchantId = 7;</code>
     */
    public long getMerchantId() {
      return merchantId_;
    }
    /**
     * <code>int64 merchantId = 7;</code>
     */
    public Builder setMerchantId(long value) {
      
      merchantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 merchantId = 7;</code>
     */
    public Builder clearMerchantId() {
      
      merchantId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object bankName_ = "";
    /**
     * <code>string bankName = 8;</code>
     */
    public java.lang.String getBankName() {
      java.lang.Object ref = bankName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bankName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bankName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBankNameBytes() {
      java.lang.Object ref = bankName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bankName = 8;</code>
     */
    public Builder setBankName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bankName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bankName = 8;</code>
     */
    public Builder clearBankName() {
      
      bankName_ = getDefaultInstance().getBankName();
      onChanged();
      return this;
    }
    /**
     * <code>string bankName = 8;</code>
     */
    public Builder setBankNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bankName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mobileNo_ = "";
    /**
     * <code>string mobileNo = 9;</code>
     */
    public java.lang.String getMobileNo() {
      java.lang.Object ref = mobileNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobileNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mobileNo = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMobileNoBytes() {
      java.lang.Object ref = mobileNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobileNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mobileNo = 9;</code>
     */
    public Builder setMobileNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mobileNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mobileNo = 9;</code>
     */
    public Builder clearMobileNo() {
      
      mobileNo_ = getDefaultInstance().getMobileNo();
      onChanged();
      return this;
    }
    /**
     * <code>string mobileNo = 9;</code>
     */
    public Builder setMobileNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mobileNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pidData_ = "";
    /**
     * <code>string pidData = 10;</code>
     */
    public java.lang.String getPidData() {
      java.lang.Object ref = pidData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pidData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pidData = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPidDataBytes() {
      java.lang.Object ref = pidData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pidData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pidData = 10;</code>
     */
    public Builder setPidData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pidData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pidData = 10;</code>
     */
    public Builder clearPidData() {
      
      pidData_ = getDefaultInstance().getPidData();
      onChanged();
      return this;
    }
    /**
     * <code>string pidData = 10;</code>
     */
    public Builder setPidDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pidData_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ipAddress_ = "";
    /**
     * <code>string ipAddress = 11;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ipAddress = 11;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ipAddress = 11;</code>
     */
    public Builder setIpAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ipAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ipAddress = 11;</code>
     */
    public Builder clearIpAddress() {
      
      ipAddress_ = getDefaultInstance().getIpAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string ipAddress = 11;</code>
     */
    public Builder setIpAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ipAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imeiMac_ = "";
    /**
     * <code>string imeiMac = 12;</code>
     */
    public java.lang.String getImeiMac() {
      java.lang.Object ref = imeiMac_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imeiMac_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imeiMac = 12;</code>
     */
    public com.google.protobuf.ByteString
        getImeiMacBytes() {
      java.lang.Object ref = imeiMac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imeiMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imeiMac = 12;</code>
     */
    public Builder setImeiMac(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imeiMac_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imeiMac = 12;</code>
     */
    public Builder clearImeiMac() {
      
      imeiMac_ = getDefaultInstance().getImeiMac();
      onChanged();
      return this;
    }
    /**
     * <code>string imeiMac = 12;</code>
     */
    public Builder setImeiMacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imeiMac_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceNo_ = "";
    /**
     * <code>string deviceNo = 13;</code>
     */
    public java.lang.String getDeviceNo() {
      java.lang.Object ref = deviceNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceNo = 13;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNoBytes() {
      java.lang.Object ref = deviceNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceNo = 13;</code>
     */
    public Builder setDeviceNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceNo = 13;</code>
     */
    public Builder clearDeviceNo() {
      
      deviceNo_ = getDefaultInstance().getDeviceNo();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceNo = 13;</code>
     */
    public Builder setDeviceNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceNo_ = value;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 userId = 14;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 14;</code>
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 14;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 15;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 15;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 15;</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 15;</code>
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 15;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <code>string city = 16;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string city = 16;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 16;</code>
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 16;</code>
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 16;</code>
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object state_ = "";
    /**
     * <code>string state = 17;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state = 17;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state = 17;</code>
     */
    public Builder setState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string state = 17;</code>
     */
    public Builder clearState() {
      
      state_ = getDefaultInstance().getState();
      onChanged();
      return this;
    }
    /**
     * <code>string state = 17;</code>
     */
    public Builder setStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      state_ = value;
      onChanged();
      return this;
    }

    private int stan_ ;
    /**
     * <code>int32 stan = 18;</code>
     */
    public int getStan() {
      return stan_;
    }
    /**
     * <code>int32 stan = 18;</code>
     */
    public Builder setStan(int value) {
      
      stan_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 stan = 18;</code>
     */
    public Builder clearStan() {
      
      stan_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bcRrn_ = "";
    /**
     * <code>string bcRrn = 19;</code>
     */
    public java.lang.String getBcRrn() {
      java.lang.Object ref = bcRrn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bcRrn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bcRrn = 19;</code>
     */
    public com.google.protobuf.ByteString
        getBcRrnBytes() {
      java.lang.Object ref = bcRrn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bcRrn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bcRrn = 19;</code>
     */
    public Builder setBcRrn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bcRrn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bcRrn = 19;</code>
     */
    public Builder clearBcRrn() {
      
      bcRrn_ = getDefaultInstance().getBcRrn();
      onChanged();
      return this;
    }
    /**
     * <code>string bcRrn = 19;</code>
     */
    public Builder setBcRrnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bcRrn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object country_ = "";
    /**
     * <code>string country = 20;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country = 20;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country = 20;</code>
     */
    public Builder setCountry(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string country = 20;</code>
     */
    public Builder clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
      onChanged();
      return this;
    }
    /**
     * <code>string country = 20;</code>
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AxisRequest)
  }

  // @@protoc_insertion_point(class_scope:AxisRequest)
  private static final com.iserveu.grpc_stub.AxisRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iserveu.grpc_stub.AxisRequest();
  }

  public static com.iserveu.grpc_stub.AxisRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AxisRequest>
      PARSER = new com.google.protobuf.AbstractParser<AxisRequest>() {
    @java.lang.Override
    public AxisRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AxisRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AxisRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AxisRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iserveu.grpc_stub.AxisRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

