// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aepsAxis.proto

package com.iserveu.grpc_stub;

public interface AxisResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AxisResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 statusCode = 50;</code>
   */
  int getStatusCode();

  /**
   * <code>int32 subStatusCode = 51;</code>
   */
  int getSubStatusCode();

  /**
   * <code>string statusDesc = 1;</code>
   */
  java.lang.String getStatusDesc();
  /**
   * <code>string statusDesc = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusDescBytes();

  /**
   * <code>string clientRefId = 2;</code>
   */
  java.lang.String getClientRefId();
  /**
   * <code>string clientRefId = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientRefIdBytes();

  /**
   * <code>string messageString = 3;</code>
   */
  java.lang.String getMessageString();
  /**
   * <code>string messageString = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageStringBytes();

  /**
   * <code>string responseCode = 4;</code>
   */
  java.lang.String getResponseCode();
  /**
   * <code>string responseCode = 4;</code>
   */
  com.google.protobuf.ByteString
      getResponseCodeBytes();

  /**
   * <code>string requestID = 5;</code>
   */
  java.lang.String getRequestID();
  /**
   * <code>string requestID = 5;</code>
   */
  com.google.protobuf.ByteString
      getRequestIDBytes();

  /**
   * <code>string amount = 6;</code>
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 6;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>string adhaarNo = 7;</code>
   */
  java.lang.String getAdhaarNo();
  /**
   * <code>string adhaarNo = 7;</code>
   */
  com.google.protobuf.ByteString
      getAdhaarNoBytes();

  /**
   * <code>string txnTime = 8;</code>
   */
  java.lang.String getTxnTime();
  /**
   * <code>string txnTime = 8;</code>
   */
  com.google.protobuf.ByteString
      getTxnTimeBytes();

  /**
   * <code>string txnDate = 9;</code>
   */
  java.lang.String getTxnDate();
  /**
   * <code>string txnDate = 9;</code>
   */
  com.google.protobuf.ByteString
      getTxnDateBytes();

  /**
   * <code>string bankName = 10;</code>
   */
  java.lang.String getBankName();
  /**
   * <code>string bankName = 10;</code>
   */
  com.google.protobuf.ByteString
      getBankNameBytes();

  /**
   * <code>string rrn = 11;</code>
   */
  java.lang.String getRrn();
  /**
   * <code>string rrn = 11;</code>
   */
  com.google.protobuf.ByteString
      getRrnBytes();

  /**
   * <code>string status = 12;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 12;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string customerMobile = 13;</code>
   */
  java.lang.String getCustomerMobile();
  /**
   * <code>string customerMobile = 13;</code>
   */
  com.google.protobuf.ByteString
      getCustomerMobileBytes();

  /**
   * <code>string availableBalance = 14;</code>
   */
  java.lang.String getAvailableBalance();
  /**
   * <code>string availableBalance = 14;</code>
   */
  com.google.protobuf.ByteString
      getAvailableBalanceBytes();

  /**
   * <code>string dispalyMessage = 15;</code>
   */
  java.lang.String getDispalyMessage();
  /**
   * <code>string dispalyMessage = 15;</code>
   */
  com.google.protobuf.ByteString
      getDispalyMessageBytes();

  /**
   * <code>string transactionStatus = 16;</code>
   */
  java.lang.String getTransactionStatus();
  /**
   * <code>string transactionStatus = 16;</code>
   */
  com.google.protobuf.ByteString
      getTransactionStatusBytes();

  /**
   * <code>string transactionDateTime = 17;</code>
   */
  java.lang.String getTransactionDateTime();
  /**
   * <code>string transactionDateTime = 17;</code>
   */
  com.google.protobuf.ByteString
      getTransactionDateTimeBytes();

  /**
   * <code>string transactionList = 18;</code>
   */
  java.lang.String getTransactionList();
  /**
   * <code>string transactionList = 18;</code>
   */
  com.google.protobuf.ByteString
      getTransactionListBytes();

  /**
   * <code>string npciTranData = 19;</code>
   */
  java.lang.String getNpciTranData();
  /**
   * <code>string npciTranData = 19;</code>
   */
  com.google.protobuf.ByteString
      getNpciTranDataBytes();

  /**
   * <code>string isFormated = 20;</code>
   */
  java.lang.String getIsFormated();
  /**
   * <code>string isFormated = 20;</code>
   */
  com.google.protobuf.ByteString
      getIsFormatedBytes();

  /**
   * <code>string systemTraceAudit = 21;</code>
   */
  java.lang.String getSystemTraceAudit();
  /**
   * <code>string systemTraceAudit = 21;</code>
   */
  com.google.protobuf.ByteString
      getSystemTraceAuditBytes();

  /**
   * <code>string localTime = 22;</code>
   */
  java.lang.String getLocalTime();
  /**
   * <code>string localTime = 22;</code>
   */
  com.google.protobuf.ByteString
      getLocalTimeBytes();

  /**
   * <code>string localDate = 23;</code>
   */
  java.lang.String getLocalDate();
  /**
   * <code>string localDate = 23;</code>
   */
  com.google.protobuf.ByteString
      getLocalDateBytes();

  /**
   * <code>string authIndentyResp = 24;</code>
   */
  java.lang.String getAuthIndentyResp();
  /**
   * <code>string authIndentyResp = 24;</code>
   */
  com.google.protobuf.ByteString
      getAuthIndentyRespBytes();

  /**
   * <code>string txnCurCode = 25;</code>
   */
  java.lang.String getTxnCurCode();
  /**
   * <code>string txnCurCode = 25;</code>
   */
  com.google.protobuf.ByteString
      getTxnCurCodeBytes();

  /**
   * <code>string uidAuthCode = 26;</code>
   */
  java.lang.String getUidAuthCode();
  /**
   * <code>string uidAuthCode = 26;</code>
   */
  com.google.protobuf.ByteString
      getUidAuthCodeBytes();

  /**
   * <code>string terminalIdenty = 27;</code>
   */
  java.lang.String getTerminalIdenty();
  /**
   * <code>string terminalIdenty = 27;</code>
   */
  com.google.protobuf.ByteString
      getTerminalIdentyBytes();

  /**
   * <code>string cardAccceptorCode = 28;</code>
   */
  java.lang.String getCardAccceptorCode();
  /**
   * <code>string cardAccceptorCode = 28;</code>
   */
  com.google.protobuf.ByteString
      getCardAccceptorCodeBytes();

  /**
   * <code>string nameLocation = 29;</code>
   */
  java.lang.String getNameLocation();
  /**
   * <code>string nameLocation = 29;</code>
   */
  com.google.protobuf.ByteString
      getNameLocationBytes();

  /**
   * <code>string ledgerBalance = 30;</code>
   */
  java.lang.String getLedgerBalance();
  /**
   * <code>string ledgerBalance = 30;</code>
   */
  com.google.protobuf.ByteString
      getLedgerBalanceBytes();
}
