// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aepsAxis.proto

package com.iserveu.grpc_stub;

public interface AxisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AxisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aadhaar = 1;</code>
   */
  java.lang.String getAadhaar();
  /**
   * <code>string aadhaar = 1;</code>
   */
  com.google.protobuf.ByteString
      getAadhaarBytes();

  /**
   * <code>string iin = 2;</code>
   */
  java.lang.String getIin();
  /**
   * <code>string iin = 2;</code>
   */
  com.google.protobuf.ByteString
      getIinBytes();

  /**
   * <code>int32 amount = 3;</code>
   */
  int getAmount();

  /**
   * <code>int64 txnId = 4;</code>
   */
  long getTxnId();

  /**
   * <code>string latitude = 5;</code>
   */
  java.lang.String getLatitude();
  /**
   * <code>string latitude = 5;</code>
   */
  com.google.protobuf.ByteString
      getLatitudeBytes();

  /**
   * <code>string longitude = 6;</code>
   */
  java.lang.String getLongitude();
  /**
   * <code>string longitude = 6;</code>
   */
  com.google.protobuf.ByteString
      getLongitudeBytes();

  /**
   * <code>int64 merchantId = 7;</code>
   */
  long getMerchantId();

  /**
   * <code>string bankName = 8;</code>
   */
  java.lang.String getBankName();
  /**
   * <code>string bankName = 8;</code>
   */
  com.google.protobuf.ByteString
      getBankNameBytes();

  /**
   * <code>string mobileNo = 9;</code>
   */
  java.lang.String getMobileNo();
  /**
   * <code>string mobileNo = 9;</code>
   */
  com.google.protobuf.ByteString
      getMobileNoBytes();

  /**
   * <code>string pidData = 10;</code>
   */
  java.lang.String getPidData();
  /**
   * <code>string pidData = 10;</code>
   */
  com.google.protobuf.ByteString
      getPidDataBytes();

  /**
   * <code>string ipAddress = 11;</code>
   */
  java.lang.String getIpAddress();
  /**
   * <code>string ipAddress = 11;</code>
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <code>string imeiMac = 12;</code>
   */
  java.lang.String getImeiMac();
  /**
   * <code>string imeiMac = 12;</code>
   */
  com.google.protobuf.ByteString
      getImeiMacBytes();

  /**
   * <code>string deviceNo = 13;</code>
   */
  java.lang.String getDeviceNo();
  /**
   * <code>string deviceNo = 13;</code>
   */
  com.google.protobuf.ByteString
      getDeviceNoBytes();

  /**
   * <code>int64 userId = 14;</code>
   */
  long getUserId();

  /**
   * <code>string userName = 15;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 15;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string city = 16;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 16;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string state = 17;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 17;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>int32 stan = 18;</code>
   */
  int getStan();

  /**
   * <code>string bcRrn = 19;</code>
   */
  java.lang.String getBcRrn();
  /**
   * <code>string bcRrn = 19;</code>
   */
  com.google.protobuf.ByteString
      getBcRrnBytes();

  /**
   * <code>string country = 20;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 20;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
